### PR TITLE
Remove an unused parameter from `Runner._withErrorHandling()` and improve its documentation

### PR DESCRIPTION
**Pull request by stmontgomery**
A small fix to remove an unused parameter from a function, and update its documentation to match the implementation.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by stmontgomery** [comment]
@swift-ci please test

**Review by grynspan — APPROVED** [review]

**Comment by stmontgomery** [comment]
@swift-ci please test macOS

**Comment by grynspan** [comment]
The macOS CI is under heavy load and your job is waiting for a free node.

**Review by briancroom — APPROVED** [review]

**Comment by grynspan** [comment]
Merging on Stuart's behalf as he is on leave.

**Pull request merged**
