### PR TITLE
Adopt swift-syntax 5.10.

### PR DESCRIPTION
**Pull request by grynspan**
This PR updates our swift-syntax dependency to the 510.0.0 tag.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Review by stmontgomery — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test Linux

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please clean test

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci pleasr test Linux

**Comment by grynspan** [comment]
@swift-ci please test Linux

**Review by briancroom — APPROVED** [review]

**Comment by stephencelis** [comment]
This unfortunately makes swift-testing incompatible with any project that depends on swift-syntax 509, either directly or via a dependency/macro library that hasn't been updated. Does swift-testing take advantage of new 510 features, or could it use a more flexible strategy, as described here: https://www.pointfree.co/blog/posts/116-being-a-good-citizen-in-the-land-of-swiftsyntax

**Comment by grynspan** [comment]
Yes, swift-testing takes advantage of swift-syntax 5.10 features.

**Pull request merged**
