### PR TITLE
[DO NOT MERGE] Swift CI Testing

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
We don't support 5.9, so we probably should delete that job outright.

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by briancroom** [comment]
Can this be closed now?

**Pull request closed without merging**
